CREATE TABLE mytable(
   Id                   INTEGER  NOT NULL PRIMARY KEY 
  ,Lien                 VARCHAR(70) NOT NULL
  ,Prénom               VARCHAR(11) NOT NULL
  ,Catégorie            VARCHAR(10) NOT NULL
  ,Sexe                 VARCHAR(28)
  ,AgeDate_de_naissance VARCHAR(10)
  ,Description          VARCHAR(470) NOT NULL
  ,Badges1              VARCHAR(22)
  ,Badges_des1          VARCHAR(30)
  ,Badges2              VARCHAR(22)
  ,Badges_des2          VARCHAR(30)
  ,Badges3              VARCHAR(22)
  ,Badges_des3          VARCHAR(30)
  ,Adresse_refuge       VARCHAR(48) NOT NULL
);
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (1,'https://pattesenrond.fr/yuki-nee-le-1-06-2020/','Yuki','Chats','Femelle','01/06/2020','À mon arrivée au refuge, je n’étais pas proche de l’humain et j''étais féroce. Aujourd’hui je suis une chatte remplie d’amour et de douceur.','Environnement sécurisé',NULL,'Caresses',NULL,'Contact avec d''autres',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (2,'https://pattesenrond.fr/charly-ne-le-19-04-2021/','Charly','Chats','Mâle','19/04/2021','J’ai été retrouvé à l''âge de 2 mois derrière un buisson, à côté d’un arrêt de bus, en bon état mais couvert de poux. Le refuge m’a accueilli et m''a permis de rejoindre une famille d’accueil avec d’autres chats. Finies les griffures et les morsures j’ai appris à devenir un chaton adorable.','Environnement sécurisé',NULL,'Contact avec d''autres',NULL,'Jouer',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (3,'https://pattesenrond.fr/pitou-ne-le-01-04-2015/','Pitou','Chats','Mâle','01/04/2015','Je vivais sur un parking et j’étais nourri par les habitants de mon quartier. À mon arrivée au refuge j’étais très maigre et mon poil était sale. J’ai rejoint une famille d’accueil où je me suis montré sociable avec chats, chiens et enfants. Je rêve de trouver un foyer qui prendra soin de moi jusqu''à la fin de ma vie.','Environnement sécurisé',NULL,'Contact avec d''autres',NULL,'Caresses',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (4,'https://pattesenrond.fr/popi-ne-le-1-01-2018/','Popi','Chats','Mâle','01/01/2018','J’ai vécu dans la rue, mon maître m’a sans doute abandonné ou perdu mais je suis en bonne santé. Actuellement en famille d’accueil,  très sociable, je recherche une famille d’adoption pour me couvrir d’amour.','Environnement sécurisé',NULL,'Contact avec d''autres',NULL,'Enfant(s)',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (5,'https://pattesenrond.fr/dolly-nee-le-25-05-2012/','Dolly','Chats','Femelle','25/05/2012','Mes anciens maîtres ont déménagé et ils ne m’avaient pas habitué à ce nouvel environnement, je me suis donc perdue, j’étais sale et maigre quand l’association m’a trouvée. Durant 4 ans, j’ai vécu la vie d’une chatte errante car mes anciens maîtres ne voulaient pas me récupérer et refusaient de me céder à l’association. Je suis revenu devant les portes de l’association et ils m’ont pris sous leurs ailes. Je recherche une famille où je pourrais pleinement m’épanouir.','Environnement sécurisé',NULL,'Calme',NULL,'Jouer',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (6,'https://pattesenrond.fr/rouky-ne-le-01-07-2018/','Rouky','Chats','Mâle','01/07/2018','Dans mon ancien foyer, un membre de la famille a déclenché une allergie. Je suis sociable et plein d’énergie.','Environnement sécurisé',NULL,'Extérieur',NULL,'Contact avec d''autres',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (7,'https://pattesenrond.fr/guimauve-ne-le-1-08-2015/','Guimauve','Chats','Mâle','01/08/2015','Je n’ai pas eu une vie facile, j’ai été abandonné.  À mon arrivée au refuge, j’étais craintif, j’avais peur des mains et il m’arrivait de mordre. Mon corps était couvert de griffures et de morsures, j’ai été testé positif au FIV (sida du chat) et au calicivirus. Peu à peu, j’ai compris que j’aimais les caresses de ma famille d’accueil en qui j’ai confiance.','Environnement sécurisé',NULL,NULL,NULL,NULL,NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (8,'https://pattesenrond.fr/oreo-ne-le-10-07-2020/','Oréo','Chats','Mâle','10/07/2020','Je suis né dans la rue mais je suis un petit chaton adorable. Ma maman Rubis est aussi au refuge, elle a fait une portée de 6 chatons mais seulement 4 dont moi ont été retrouvés.','Environnement sécurisé',NULL,'Contact avec d''autres',NULL,'Caresses',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (9,'https://pattesenrond.fr/neha-nee-en-mars-2019/','Neha','Chats','Mâle','mars 2019','J’errais dans la rue suite aux décès de mon propriétaire, le refuge m''a recueilli et j’ai été placée en famille d’accueil qui gagne ma confiance petit à petit.','Contact avec d''autres',NULL,'Jouer',NULL,'Calme',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (10,'https://pattesenrond.fr/croquette-ne-le-09-08-2016/','Croquette','Chats','Mâle','09/08/2016','J’ai vécu dans la rue, j’ai déjà été pris en charge par une association puis l’association Pattenrond m’a placée dans une famille d’accueil qui correspond à mes besoins. Je ne suis pas très proche des humains, une cohabitation bienveillante me suffit.','Calme',NULL,'Jouer',NULL,'Contact avec d''autres',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (11,'https://pattesenrond.fr/noushka-nee-en-2017/','Noushka','Chats','Mâle','2017','Mes anciens propriétaires m’ont mis dans une cage de transport puis m’ont déposé dehors sur un trottoir, avec la porte de la cage ouverte. J’étais terrorisée, je ne me suis pas enfuie, quelqu’un m’a trouvé et m’a emmené chez le vétérinaire. Un des bénévoles de PattenRond  se trouvait à la clinique et il a décidé de me prendre sous son aile.','Contact avec d''autres',NULL,'Extérieur',NULL,'Jouer',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (12,'https://pattesenrond.fr/namour-nee-en-avril-2017/','Namour','Chats','Femelle','avril 2017','Je cherche une famille qui prendra le temps de gagner ma confiance, avec de la patience et beaucoup d’amour.','Extérieur',NULL,'Caresses',NULL,'Contact avec d''autres',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (13,'https://pattesenrond.fr/krokmou-nee-en-avril-2017/','Krokmou','Chats','Femelle','avril 2017','J’ai été prise en charge à l''âge de 2 mois par l’association avec ma sœur. Un mois plus tard, elle a été adoptée et j’ai été testée positive au calicivirus. Moi, je suis toujours là à attendre ma famille qui saura m’offrir une vie pleine de bonheur.','Extérieur',NULL,'Caresses',NULL,'Jouer',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (14,'https://pattesenrond.fr/onyx-ne-en-2018/','Onyx','Chats','Mâle','2018','J’ai été sorti de fourrière par l’association Pattenrond. J’aime autant jouer et courir partout que me reposer quand il le faut.','Caresses',NULL,'Jouer',NULL,'Contact avec d''autres',NULL,'164 Rue Rousseau Vaudran, 77190 Dammarie-les-Lys');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (15,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-sept','Deux','Reptiles','Femelle','2015','Je suis un python royal et je mesure 1m20. J''ai un régime particulier, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.','Autonomie',NULL,'Calme',NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (16,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-herma-1','Joyeux','Reptiles','Non identifiable avant 4 ans','Aout 2020','Je suis une tortue des Balkans, je mesure environ 6 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages.','Environnement sécurisé',NULL,'Calme',NULL,'Extérieur',NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (17,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-wooper','Freddy','Reptiles','Mâle',NULL,'Je suis un varan des savanes, ma taille est de 90 cm. Je suis carnivore. J’ai été brûlé sur le dos et le ventre, j’en garde des traces et reste fragile.','Calme',NULL,'Environnement sécurisé',NULL,'Extérieur',NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (18,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-rock','Cardi','Poissons','Mâle',NULL,'Je suis un crabe tricolore et je suis omnivore, j’adore particulièrement les insectes et les végétaux. On me surnomme le “bulldozer”  car j’aime retourner la terre pour me créer des nouvelles cachettes.',NULL,NULL,'Autonomie',NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (19,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-deux','Huit','Reptiles',NULL,'2015','Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.','Calme',NULL,'Environnement sécurisé',NULL,'Autonomie',NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (20,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-sacpa-1','Marsu','Reptiles','Femelle','2010','Je suis une tortue mauresque, je mesure environ 18 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages.','Hibernation',NULL,'Extérieur',NULL,'Environnement sécurisé',NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (21,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-gabi','Rango','Reptiles','Mâle','2015','Je suis un dragon barbu, j’ai été retrouvé dehors puis gardé sans UV pendant plusieurs mois. J’ai donc des problèmes pour me déplacer.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (22,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-sungaya','Peruphasma','Insectes',NULL,NULL,'Je suis un phasme du Pérou et je mesure de 1 à 8 cm selon l''âge. Je suis herbivore le lilas, le troène, le chèvrefeuille ou le lierre j’adore ca.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (23,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-quatre','Sept','Reptiles','Femelle','2017','Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (24,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-sushi-1','Rapido','Reptiles','Mâle','2010','Je suis une tortue aquatique qui mesure environ 20cm, je suis carnivore. J’ai besoin d’un grand aquarium pour me sentir bien.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (25,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-cr%C3%AAtou','Kacchan','Reptiles','Femelle','2018','Je suis un lézard ou plus précisément un Gecko tokay. Je mesure 20 cm et je suis insectivore. Je suis timide et je vis dans un terrarium arbiricole.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (26,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-escobar','King Julian','Reptiles','Mâle','2009','Je suis le serpent roi de Californie, de nature grand je mesure 1m10. Je suis carnivore et adore manger des souris. Je suis dynamique, j’aime me balader et me cacher dans mon terrarium terrestre.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (27,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-diego','Sushi','Reptiles','Femelle','5 ans','Je suis une tortue aquatique qui mesure environ 20 cm, je suis carnivore. J’ai besoin d’un grand aquarium pour me sentir bien.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (28,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-kiwi','Skull','Reptiles',NULL,NULL,'Je suis un iguane vert et je mesure 1m50. Je suis herbivore. Je ne suis pas habitué à côtoyer les humains, il me faudra un temps d''adaptation et d’éducation.  Je vis dans un terrarium humide.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (29,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-chamallow','Fantomas','Amphibiens','Femelle',NULL,'Je suis un axolotl et je mesure environ 20 cm. Je suis carnivore. Je vis dans un grand aquarium.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (30,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-pyhon-1-1','Black','Reptiles','Mâle','2013','Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.','Calme',NULL,'Environnement sécurisé',NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (31,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-sushi-3','Chamallow','Amphibiens','Femelle',NULL,'Je suis un axolotl et je mesure environ 20 cm. Je suis carnivore. Je vis dans un grand aquarium.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (32,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-aqua-2','Drago','Reptiles','Mâle','2016','Je suis un dragon d’eau, ma taille est de 40 cm. Je suis omnivore, les insectes, les végétaux j’en réclame ! De nature timide, je vis dans un terrarium humide',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (33,'https://sosptitesbetes.wixsite.com/sosptitesbetes/sungaya','Sungaya','Insectes',NULL,NULL,'Je suis un phasme épineux, je suis herbivore, j’aime particulièrement les ronces, le lierre et le chêne. Je vis dans un petit terrarium ou flexarium au choix.','Calme',NULL,'Autonomie',NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (34,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-casper','Hélio','Reptiles','Mâle','2016','Je suis un boa constricteur de Colombie et je mesure 1m70. Je suis carnivore, mon petit plaisir c’est les rats. Je suis de caractère vif et je vis dans un terrarium.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (35,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-marsu','Toca','Reptiles','Mâle','1990','Je suis une tortue mauresque, je mesure environ 20 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages. Je vis dans un jardin.','Hibernation',NULL,'Extérieur',NULL,'Environnement sécurisé',NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (36,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-drago','Rango2','Reptiles','Mâle','2018','Je suis un dragon d’eau, ma taille est de 80 cm. Je suis omnivore, les insectes, les végétaux j’en réclame ! De nature timide, je vis dans un terrarium humide.',NULL,NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
INSERT INTO mytable(Id,Lien,Prénom,Catégorie,Sexe,AgeDate_de_naissance,Description,Badges1,Badges_des1,Badges2,Badges_des2,Badges3,Badges_des3,Adresse_refuge) VALUES (37,'https://sosptitesbetes.wixsite.com/sosptitesbetes/copie-de-huit','Ninja','Reptiles','Mâle','2019','Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.','Calme',NULL,NULL,NULL,NULL,NULL,'7 imp du Moulin Fouleret, 91150 Etampes');
