-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 09:43:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `adresse_mail` VARCHAR(45) NULL,
  `url_photo` VARCHAR(45) NULL,
  `date_naissance` DATE NULL,
  `adresse` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_derniere_connexion` DATETIME NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `types_animaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `types_animaux` (
  `idtypes_animaux` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `url_icone` VARCHAR(45) NULL,
  PRIMARY KEY (`idtypes_animaux`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profil_animal_de_compagnie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profil_animal_de_compagnie` (
  `idprofil_animal_de_compagnie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `url_photo` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `date_naissance` DATE NULL,
  `utilisateur_idutilisateur1` INT NOT NULL,
  `types_animaux_idtypes_animaux` INT NOT NULL,
  PRIMARY KEY (`idprofil_animal_de_compagnie`, `utilisateur_idutilisateur1`, `types_animaux_idtypes_animaux`),
  INDEX `fk_profil_animal_de_compagnie_utilisateur2_idx` (`utilisateur_idutilisateur1` ASC),
  INDEX `fk_profil_animal_de_compagnie_types_animaux1_idx` (`types_animaux_idtypes_animaux` ASC),
  CONSTRAINT `fk_profil_animal_de_compagnie_utilisateur2`
    FOREIGN KEY (`utilisateur_idutilisateur1`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profil_animal_de_compagnie_types_animaux1`
    FOREIGN KEY (`types_animaux_idtypes_animaux`)
    REFERENCES `types_animaux` (`idtypes_animaux`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `media` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `date_publication` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_likes_utilisateurs` INT NULL,
  `profil_animal_de_compagnie_idprofil_animal_de_compagnie` INT NOT NULL,
  `profil_animal_de_compagnie_utilisateur_idutilisateur1` INT NOT NULL,
  PRIMARY KEY (`idpost`, `profil_animal_de_compagnie_idprofil_animal_de_compagnie`, `profil_animal_de_compagnie_utilisateur_idutilisateur1`),
  INDEX `fk_post_profil_animal_de_compagnie1_idx` (`profil_animal_de_compagnie_idprofil_animal_de_compagnie` ASC, `profil_animal_de_compagnie_utilisateur_idutilisateur1` ASC),
  CONSTRAINT `fk_post_profil_animal_de_compagnie1`
    FOREIGN KEY (`profil_animal_de_compagnie_idprofil_animal_de_compagnie` , `profil_animal_de_compagnie_utilisateur_idutilisateur1`)
    REFERENCES `profil_animal_de_compagnie` (`idprofil_animal_de_compagnie` , `utilisateur_idutilisateur1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversation` (
  `idconversation` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `url_photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idconversation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `texte_message` TINYTEXT NULL,
  `url_media` VARCHAR(45) NULL,
  `date_envoi_msg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `utilisateur_idutilisateur` INT NOT NULL,
  `conversation_idconversation` INT NOT NULL,
  PRIMARY KEY (`idmessage`, `utilisateur_idutilisateur`, `conversation_idconversation`),
  INDEX `fk_message_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  INDEX `fk_message_conversation1_idx` (`conversation_idconversation` ASC),
  CONSTRAINT `fk_message_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_conversation1`
    FOREIGN KEY (`conversation_idconversation`)
    REFERENCES `conversation` (`idconversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorie_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorie_forum` (
  `idcategories_forum` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `url_icone` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategories_forum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sujet_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sujet_forum` (
  `idsujet_forum` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `id_reponse_epinglee` INT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  `categorie_forum_idcategories_forum` INT NOT NULL,
  PRIMARY KEY (`idsujet_forum`, `utilisateur_idutilisateur`, `categorie_forum_idcategories_forum`),
  INDEX `fk_sujet_forum_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  INDEX `fk_sujet_forum_categorie_forum1_idx` (`categorie_forum_idcategories_forum` ASC),
  CONSTRAINT `fk_sujet_forum_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sujet_forum_categorie_forum1`
    FOREIGN KEY (`categorie_forum_idcategories_forum`)
    REFERENCES `categorie_forum` (`idcategories_forum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reponse_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reponse_forum` (
  `idreponse_forum` INT NOT NULL AUTO_INCREMENT,
  `texte_reponse` MEDIUMTEXT NULL,
  `date_publication` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_likes_utilisateurs` INT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idreponse_forum`, `utilisateur_idutilisateur`),
  INDEX `fk_reponse_forum_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_reponse_forum_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sujet_forum_has_reponse_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sujet_forum_has_reponse_forum` (
  `sujet_forum_idsujet_forum` INT NOT NULL,
  `sujet_forum_utilisateur_idutilisateur` INT NOT NULL,
  `reponse_forum_idreponse_forum` INT NOT NULL,
  PRIMARY KEY (`sujet_forum_idsujet_forum`, `sujet_forum_utilisateur_idutilisateur`, `reponse_forum_idreponse_forum`),
  INDEX `fk_sujet_forum_has_reponse_forum_reponse_forum1_idx` (`reponse_forum_idreponse_forum` ASC),
  INDEX `fk_sujet_forum_has_reponse_forum_sujet_forum1_idx` (`sujet_forum_idsujet_forum` ASC, `sujet_forum_utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_sujet_forum_has_reponse_forum_sujet_forum1`
    FOREIGN KEY (`sujet_forum_idsujet_forum` , `sujet_forum_utilisateur_idutilisateur`)
    REFERENCES `sujet_forum` (`idsujet_forum` , `utilisateur_idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sujet_forum_has_reponse_forum_reponse_forum1`
    FOREIGN KEY (`reponse_forum_idreponse_forum`)
    REFERENCES `reponse_forum` (`idreponse_forum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversation_has_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversation_has_utilisateur` (
  `conversation_idconversation` INT NOT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`conversation_idconversation`, `utilisateur_idutilisateur`),
  INDEX `fk_conversation_has_utilisateur_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  INDEX `fk_conversation_has_utilisateur_conversation1_idx` (`conversation_idconversation` ASC),
  CONSTRAINT `fk_conversation_has_utilisateur_conversation1`
    FOREIGN KEY (`conversation_idconversation`)
    REFERENCES `conversation` (`idconversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog` (
  `idblog` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `url_contenu_article` VARCHAR(45) NULL,
  `date_publication` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idblog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `refuge` (
  `idrefuge` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `lien` VARCHAR(45) NULL,
  `adresse_mail` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `adresse` VARCHAR(45) NULL,
  `url_logo` VARCHAR(45) NULL,
  PRIMARY KEY (`idrefuge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animal_a_adopter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animal_a_adopter` (
  `idanimal_a_adopter` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `date_anniversaire` DATE NULL,
  `refuge_idrefuge` INT NOT NULL,
  PRIMARY KEY (`idanimal_a_adopter`, `refuge_idrefuge`),
  INDEX `fk_animal_a_adopter_refuge1_idx` (`refuge_idrefuge` ASC),
  CONSTRAINT `fk_animal_a_adopter_refuge1`
    FOREIGN KEY (`refuge_idrefuge`)
    REFERENCES `refuge` (`idrefuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utilisateur_has_animal_a_adopter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utilisateur_has_animal_a_adopter` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `animal_a_adopter_idanimal_a_adopter` INT NOT NULL,
  `animal_a_adopter_refuge_idrefuge` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `animal_a_adopter_idanimal_a_adopter`, `animal_a_adopter_refuge_idrefuge`),
  INDEX `fk_utilisateur_has_animal_a_adopter_animal_a_adopter1_idx` (`animal_a_adopter_idanimal_a_adopter` ASC, `animal_a_adopter_refuge_idrefuge` ASC),
  INDEX `fk_utilisateur_has_animal_a_adopter_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_animal_a_adopter_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_animal_a_adopter_animal_a_adopter1`
    FOREIGN KEY (`animal_a_adopter_idanimal_a_adopter` , `animal_a_adopter_refuge_idrefuge`)
    REFERENCES `animal_a_adopter` (`idanimal_a_adopter` , `refuge_idrefuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badge` (
  `idbadge` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `url_icone` VARCHAR(45) NULL,
  PRIMARY KEY (`idbadge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animal_a_adopter_has_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animal_a_adopter_has_badge` (
  `animal_a_adopter_idanimal_a_adopter` INT NOT NULL,
  `animal_a_adopter_refuge_idrefuge` INT NOT NULL,
  `badge_idbadge` INT NOT NULL,
  PRIMARY KEY (`animal_a_adopter_idanimal_a_adopter`, `animal_a_adopter_refuge_idrefuge`, `badge_idbadge`),
  INDEX `fk_animal_a_adopter_has_badge_badge1_idx` (`badge_idbadge` ASC),
  INDEX `fk_animal_a_adopter_has_badge_animal_a_adopter1_idx` (`animal_a_adopter_idanimal_a_adopter` ASC, `animal_a_adopter_refuge_idrefuge` ASC),
  CONSTRAINT `fk_animal_a_adopter_has_badge_animal_a_adopter1`
    FOREIGN KEY (`animal_a_adopter_idanimal_a_adopter` , `animal_a_adopter_refuge_idrefuge`)
    REFERENCES `animal_a_adopter` (`idanimal_a_adopter` , `refuge_idrefuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_a_adopter_has_badge_badge1`
    FOREIGN KEY (`badge_idbadge`)
    REFERENCES `badge` (`idbadge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centres_interet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centres_interet` (
  `idcentres_interet` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idcentres_interet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utilisateur_has_centres_interet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utilisateur_has_centres_interet` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `centres_interet_idcentres_interet` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `centres_interet_idcentres_interet`),
  INDEX `fk_utilisateur_has_centres_interet_centres_interet1_idx` (`centres_interet_idcentres_interet` ASC),
  INDEX `fk_utilisateur_has_centres_interet_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_centres_interet_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_centres_interet_centres_interet1`
    FOREIGN KEY (`centres_interet_idcentres_interet`)
    REFERENCES `centres_interet` (`idcentres_interet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signalement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `signalement` (
  `idsignalement` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `message` MEDIUMTEXT NULL,
  `url_photo` VARCHAR(45) NULL,
  `date_signalement` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `statut` TINYINT NULL DEFAULT 0,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idsignalement`, `utilisateur_idutilisateur`),
  INDEX `fk_signalement_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_signalement_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liste_amis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liste_amis` (
  `idliste_amis` INT NOT NULL AUTO_INCREMENT,
  `id_demandeur` INT NULL,
  `id_receveur` INT NULL,
  `date_demande` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_bloqueur` INT NULL,
  PRIMARY KEY (`idliste_amis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sujet_forum_favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sujet_forum_favoris` (
  `idsujet_forum_favoris` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `id_sujet_favoris` INT NULL,
  PRIMARY KEY (`idsujet_forum_favoris`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centres_interet_has_types_animaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centres_interet_has_types_animaux` (
  `centres_interet_idcentres_interet` INT NOT NULL,
  `types_animaux_idtypes_animaux` INT NOT NULL,
  PRIMARY KEY (`centres_interet_idcentres_interet`, `types_animaux_idtypes_animaux`),
  INDEX `fk_centres_interet_has_types_animaux_types_animaux1_idx` (`types_animaux_idtypes_animaux` ASC),
  INDEX `fk_centres_interet_has_types_animaux_centres_interet1_idx` (`centres_interet_idcentres_interet` ASC),
  CONSTRAINT `fk_centres_interet_has_types_animaux_centres_interet1`
    FOREIGN KEY (`centres_interet_idcentres_interet`)
    REFERENCES `centres_interet` (`idcentres_interet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centres_interet_has_types_animaux_types_animaux1`
    FOREIGN KEY (`types_animaux_idtypes_animaux`)
    REFERENCES `types_animaux` (`idtypes_animaux`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reinitialisation_mot_de_passe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reinitialisation_mot_de_passe` (
  `idreinitialisation_mot_de_passe` INT NOT NULL AUTO_INCREMENT,
  `id_demandeur` INT NULL,
  `token_reinitialisation` VARCHAR(45) NULL,
  `date_demande_reinitialisation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreinitialisation_mot_de_passe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commentaire_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commentaire_post` (
  `idcommentaire_post` INT NOT NULL AUTO_INCREMENT,
  `texte_commentaire` MEDIUMTEXT NULL,
  `date_publication` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `utilisateur_idutilisateur` INT NOT NULL,
  `post_idpost` INT NOT NULL,
  `post_profil_animal_de_compagnie_idprofil_animal_de_compagnie` INT NOT NULL,
  `post_profil_animal_de_compagnie_utilisateur_idutilisateur1` INT NOT NULL,
  PRIMARY KEY (`idcommentaire_post`, `utilisateur_idutilisateur`, `post_idpost`, `post_profil_animal_de_compagnie_idprofil_animal_de_compagnie`, `post_profil_animal_de_compagnie_utilisateur_idutilisateur1`),
  INDEX `fk_commentaire_post_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  INDEX `fk_commentaire_post_post1_idx` (`post_idpost` ASC, `post_profil_animal_de_compagnie_idprofil_animal_de_compagnie` ASC, `post_profil_animal_de_compagnie_utilisateur_idutilisateur1` ASC),
  CONSTRAINT `fk_commentaire_post_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_post_post1`
    FOREIGN KEY (`post_idpost` , `post_profil_animal_de_compagnie_idprofil_animal_de_compagnie` , `post_profil_animal_de_compagnie_utilisateur_idutilisateur1`)
    REFERENCES `post` (`idpost` , `profil_animal_de_compagnie_idprofil_animal_de_compagnie` , `profil_animal_de_compagnie_utilisateur_idutilisateur1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
