-- phpMyAdmin SQL Dump
-- version 4.9.10
-- https://www.phpmyadmin.net/
--
-- Hôte : db5006335318.hosting-data.io
-- Généré le : ven. 04 mars 2022 à 00:17
-- Version du serveur : 5.7.36-log
-- Version de PHP : 7.0.33-0+deb9u12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `dbs5282415`
--

--
-- Déchargement des données de la table `animal_a_adopter`
--

INSERT INTO `animal_a_adopter` (`idanimal_a_adopter`, `nom`, `sexe`, `photo`, `description`, `date_anniversaire`, `refuge_idrefuge`, `idtype`) VALUES
(42, 'Yuki', 1, '11642452446.jpg', 'À mon arrivée au refuge, je n’étais pas proche de l’humain et j\'étais féroce. Après une sociabilisation de plusieurs mois, je me suis transformée. Aujourd\'hui j\'ai besoin d’être liée avec mon humain. Je sais me faire entendre par mes petits « miaous » quand je vous vois rentrer dans la pièce où je me trouve, je viens me frotter à vos jambes pour dire bonjour. Mon moment préféré c\'est le soir quand je réclame des caresses au lit avec beaucoup d’enthousiasme, je ronronne au moindre frôlement. Je suis une chatte très câline une fois en confiance !', '2020-06-01', 11, 2),
(45, 'Charly', 0, '11642454483.jpg', 'J’ai été retrouvé à l\'âge de 2 mois derrière un buisson, à côté d’un arrêt de bus, en bon état mais couvert de poux. Le refuge m’a accueilli et m\'a permis de rejoindre une famille d’accueil avec d’autres chats et un chien. Finies les griffures et les morsures j’ai appris à devenir un chaton adorable. Très joueur, je m’amuse d’un rien comme par exemple les ombres (qui peuvent m’occuper un certain temps !). J\'adore les câlins que je réclame avec beaucoup de ronrons. Je suis fin prêt pour débuter une nouvelle vie et je n’attends plus que vous !', '2021-04-19', 11, 2),
(51, 'Pitou', 0, '11642455208.jpg', 'Je vivais sur un parking et j’étais nourri par les habitants de mon quartier. À mon arrivée au refuge j’étais très maigre et mon poil était sale. J’ai rejoint une famille d’accueil où je me suis montré sociable avec chats, chiens et enfants. Pas spécialement gourmand, je ne suis pas un chat que l’on peut amadouer par l’estomac. Mais j\'aime les câlins et particulièrement les caresses. Je rêve de trouver un foyer qui prendra soin de moi jusqu\'à la fin de ma vie.', '2015-04-01', 11, 2),
(54, 'Popi', 0, '11642456142.jpg', 'J’ai vécu dans la rue, mon maître m’a sans doute abandonné ou perdu mais je suis en bonne santé. J\'adore les caresses et je suis très sociable même avec les inconnus vers qui je vais avec facilité. Actuellement en famille d’accueil, je recherche une famille d’adoption pour me couvrir d’amour. J\'aime les autres chats avec qui j\'adore jouer volontiers et sauter dans tous les sens pour attraper le plumeau, je serais super heureux d’avoir un congénère pour m’amuser !', '2018-01-01', 11, 2),
(59, 'Rouky', 0, '11642458436.jpg', 'Dans mon ancien foyer, un membre de la famille a déclenché une allergie. Un peu chamboulé par mon arrivée au refuge, j\'ai néanmoins apprécié la présence d’un autre chat pour me réconforter. Je suis sociable avec l’humain et j\'aime me prélasser dans des positions aussi adorables les unes que les autres. Très joueur et plein d’énergie j\'ai besoin de me dépenser. La présence d’un jardin sécurisé dans ma famille d’adoption serait un grand bonheur pour moi. Je passe aussi beaucoup de temps à observer par la fenêtre ! Avec le temps, j\'apprécie davantage les câlins, bien que ce ne soit toujours pas ce que je préfère.', '2018-07-01', 11, 2),
(63, 'Rango', 0, '31642508121.jpg', 'Je suis un dragon barbu, j’ai été retrouvé dehors puis gardé sans UV pendant plusieurs mois. J’ai donc des problèmes pour me déplacer.', '2015-01-01', 12, 6),
(64, 'Joyeux', 0, '31642522586.jpg', 'Je suis une tortue des Balkans, je mesure environ 6 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages.', '2020-08-01', 12, 6),
(66, 'Deux', 1, '31642537192.jpg', 'Je suis un python royal et je mesure 1m20. J\'ai un régime particulier, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2015-01-01', 12, 6),
(67, 'Guimauve', 0, '31642537528.jpeg', 'Je n’ai pas eu une vie facile, j’ai été abandonné.  À mon arrivée au refuge, j’étais craintif, j’avais peur des mains et il m’arrivait de mordre. Mon corps était couvert de griffures et de morsures, j’ai été testé positif au FIV (sida du chat) et au calicivirus. Néanmoins, je n’ai fait qu’une crise en deux ans et, après une extraction dentaire et une antibiothérapie, j\'ai repris le cours de ma vie. Je ne pourrais pas être au contact d’autres chats au risque de les contaminer, mais peu importe car ma passion suprême, c’est l’humain ! Peu à peu, j’ai compris que j’aimais les caresses de ma famille d’accueil en qui j’ai confiance.  Je n’aime pas la solitude. Je suis indépendant mais j\'aime avoir la présence réconfortante de mon humain à la maison, j\'aime le suivre partout comme un chien et s’intéresser à tout ce qu’il fait.', '2015-08-01', 11, 2),
(68, 'Sept', 1, '31642537848.jpg', 'Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2017-01-01', 12, 6),
(69, 'Oréo', 0, '31642538106.jpeg', 'Je suis né dans la rue mais je suis un petit chaton adorable. Ma maman Rubis est aussi au refuge, elle a fait une portée de 6 chatons mais seulement 4 ont été retrouvé. J\'aime courir en crabe pour épater mes copains ou le chien de ma famille d’accueil. Bien que joueur et très proche des autres chatons, je suis un bébé au caractère tranquille. Je suis doux, je ne mets jamais les griffes et je ne fais pas de bêtises ! J\'aime me hisser sur les genoux de ma famille d’accueil pour avoir mon compte de papouilles.', '2020-07-10', 11, 2),
(74, 'Croquette', 0, '31642539463.jpg', 'J’ai vécu dans la rue, j’ai déjà été pris en charge par une première association qui m’a stérilisé et ma gardé un certain temps puis l’association Pattes-En-Rond m’a placée dans une famille d’accueil qui correspond à mes besoins. Je ne suis pas très proche des humains, une cohabitation bienveillante me suffit. J\'aime jouer et j’y prends beaucoup de plaisir, j\'aime la bonne nourriture et m’étaler partout. Je m’entends si bien avec les autres chats, je ferais le compagnon parfait. ', '2016-08-09', 11, 2),
(76, 'Noushka', 0, '31642539819.jpg', 'Mes anciens propriétaires m’ont mis dans une cage de transport puis ils m’ont déposé dehors sur un trottoir, avec la porte de la cage ouverte. J’étais terrorisée, je ne me suis pas enfuie, quelqu’un m’a trouvé et m’a emmené chez le vétérinaire. Un des bénévoles de Pattes-En-Rond  se trouvait à la clinique et il a décidé de me prendre sous son aile. Je ne suis pas une minette câline et douce que l’on peut papouiller des heures, je suis une tornade qui a besoin d’être occupée ! Adoratrice du moindre objet avec lequel jouer, je me jette sur les plumeaux, joue des heures avec une balle, saute après les ombres et cherche toujours quelque chose à faire ! ', '2017-01-01', 11, 2),
(79, 'Krokmou', 1, '31642540329.jpg', 'J’ai été prise en charge à l\'âge de 2 mois par l’association avec ma sœur. Un mois plus tard, elle a été adoptée et j’ai été testée positive au calicivirus. Je suis une petite timide qui a besoin d’observer avant de faire confiance. Moi, je suis toujours là à attendre ma famille qui saura m’offrir une vie pleine de bonheur. ', '2017-04-01', 11, 2),
(80, 'Black', 0, '31642541404.jpg', 'Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2013-01-01', 12, 6),
(82, 'Cardi', 0, '31642590650.jpg', 'Je suis un crabe tricolore et je suis omnivore, j’adore particulièrement les insectes et les végétaux. On me surnomme le “bulldozer” car j’aime retourner la terre pour me créer des nouvelles cachettes.', '0001-01-01', 12, 8),
(84, 'Peruphasma', 1, '31642591104.jpg', 'Je suis un phasme du Pérou et je mesure de 1 à 8 cm selon l\'âge. Je suis herbivore le lilas, le troène, le chèvrefeuille ou le lierre j’adore ca.', '0001-01-01', 12, 9),
(85, 'Marsu', 1, '31642614023.jpg', 'Je suis une tortue mauresque, je mesure environ 18 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages.', '2010-01-01', 12, 6),
(86, 'Sushi', 1, '31642614182.jpg', 'Je suis une tortue aquatique qui mesure environ 20 cm, je suis carnivore. J’ai besoin d’un grand aquarium pour me sentir bien.', '2017-01-01', 12, 6),
(87, 'Dolly', 1, '31642614342.jpg', 'Mes anciens maîtres ont déménagé et ils ne m’avaient pas habitué à ce nouvel environnement, je me suis donc perdue, j’étais sale et maigre quand l’association m’a trouvée. Durant 4 ans, j’ai vécu la vie d’une chatte errante car mes anciens maîtres ne voulaient pas me récupérer et refusaient de me céder à l’association. Je suis revenu devant les portes de l’association et ils m’ont pris sous leurs ailes. Je suis une chatte sauvage qui n’est pas proche de l’humain. Mais je suis une adorable petite minette timide mais sociable, calme et goulue. Je recherche une famille où je pourrais pleinement m’épanouir.', '2012-05-25', 11, 2),
(88, 'Onyx', 0, '31642614590.jpg', 'J’ai été sorti de fourrière par l’association Pattes-En-Rond. J\'adore les câlins, c’est ma grande passion ! J\'aime bien jouer et j\'use beaucoup de temps à chasser les mouches ou tout autre petit insecte. Parfois, je me transforme en pile et court partout pour mon quart d’heure de folie. Mais je suis aussi un chat clown, pas agile pour deux sous, qui loupe régulièrement ses sauts, un peu patapouf au temps de réaction allongé !  J\'aime bien faire dodo dans des petits recoins au chaud. Et des siestes contre mes humains. ', '2018-01-01', 11, 2),
(89, 'Skull', 2, '31642614790.jpg', 'Je suis un iguane vert et je mesure 1m50. Je suis herbivore. Je ne suis pas habitué à côtoyer les humains, il me faudra un temps d\'adaptation et d’éducation. Je vis dans un terrarium humide.', '0001-01-01', 12, 6),
(90, 'Sungaya', 2, '31642614914.jpg', 'Je suis un phasme épineux, je suis herbivore, j’aime particulièrement les ronces, le lierre et le chêne. Je vis dans un petit terrarium ou flexarium au choix.', '0001-01-01', 12, 9),
(91, 'Namour', 1, '31642615066.jpg', 'Je cherche une famille qui prendra le temps de gagner ma confiance, avec de la patience et beaucoup d’amour. J\'adore les papouilles une fois que je me sens bien et j\'adore être dehors pour observer les oiseaux et y rester même sous la pluie ou dans la neige ! J\' aime quand même venir au chaud dormir sur le lit quand tout le monde dort et me laisser câliner le matin avec plaisir. Je cherche une famille qui prendra le temps de gagner ma confiance, avec de la patience et beaucoup d’amour.', '2017-04-01', 11, 2),
(92, 'Rapido', 0, '31642615208.jpg', 'Je suis une tortue aquatique qui mesure environ 20cm, je suis carnivore. J’ai besoin d’un grand aquarium pour me sentir bien.', '2010-01-01', 12, 6),
(93, 'Rango2', 0, '31642615531.jpg', 'Je suis un dragon d’eau, ma taille est de 80 cm. Je suis omnivore, les insectes, les végétaux j’en réclame ! De nature timide, je vis dans un terrarium humide.', '2018-01-01', 12, 6),
(94, 'Drago', 0, '31642615604.jpg', 'Je suis un dragon d’eau, ma taille est de 40 cm. Je suis omnivore, les insectes, les végétaux j’en réclame ! De nature timide, je vis dans un terrarium humide', '2016-01-01', 12, 6),
(95, 'Toca', 0, '31642615732.jpg', 'Je suis une tortue mauresque, je mesure environ 20 cm et mon espérance de vie est de 100 ans. Je suis végétarien, je me nourris principalement de plantes sauvages. Je vis dans un jardin.', '1990-01-01', 12, 6),
(96, 'Kacchan', 1, '31642615958.jpg', 'Je suis un lézard ou plus précisément un Gecko tokay. Je mesure 20 cm et je suis insectivore. Je suis timide et je vis dans un terrarium arbiricole.', '2018-01-01', 12, 6),
(97, 'Huit', 2, '31642616095.jpg', 'Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2015-01-01', 12, 6),
(98, 'Ninja', 0, '31642616217.jpg', 'Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2019-01-01', 12, 6),
(99, 'Potiron', 0, '31642616325.jpg', 'J’ai été pris en charge alors que j’errais dans les rues de Dammarie les lys. Atteint de la teigne, j’ai été soigné et je recherche maintenant une famille prête à m’adopter et qui prendra soin de moi. J\'aime m’étaler sur le dos pour qu’on me patouille tout le corps, il n\'y a pas un centimètre où je n’accepte pas les caresses. Le ventre ? J\'adore ! Je suis hyper sociable avec tous les animaux, humains et non-humains, et je sais être très doux avec les enfants. Je ne mets jamais les griffes, je n’ai jamais un brin d’agressivité même je suis stressé. Très très joueur j\'adore le plumeau. J\'aime tellement ça que je me jette quasiment sur les murs pour l’attraper tellement. ', '2020-11-11', 11, 2),
(102, 'Kiara', 1, '31642623943.jpg', 'Je suis un boa constrictor. Je suis carnivore, je mange un rat de 150g tous les 15 jours. Je suis méfiante. Je vis dans un grand terrarium avec des branches et des endroits pour me cacher, j’aime aussi me baigner dans un grand bac d’eau.', '2013-01-01', 12, 6),
(103, 'Bagui', 0, '31642624364.jpg', 'Je suis un pogona vitticeps, je suis omnivore et très gourmand les insectes et les végétaux j’en réclame ! Je vis dans un terrarium désertique.', '2013-01-01', 12, 6),
(104, 'Domino', 2, '31642625223.jpg', 'Je suis un lampropeltis californiae, je mesure environ 90cm. Je suis carnivore, je mange une souris adulte une fois toutes les deux semaines. Je vis dans un terrarium terrestre.', '2018-01-01', 12, 6),
(108, 'Vitti', 1, '31642625990.jpg', 'Je suis un pogona vitticeps, je suis omnivore et très gourmande, les insectes et les végétaux j’en réclame ! Je vis dans un terrarium désertique.', '2018-01-01', 12, 6),
(109, 'Pei', 1, '31642626136.jpg', 'Je suis un pogona vitticeps, je suis omnivore les insectes et les végétaux j’en réclame ! Je vis dans un terrarium désertique.', '2015-01-01', 12, 6),
(110, 'Akan', 0, '31642626347.jpg', 'Je suis un boa constrictor, je mesure 1,3 m. Je suis carnivore, je mange un rat de 150g tous les 15 jours. Je vis dans un grand terrarium avec des branches et des endroits pour me cacher, j’aime aussi me baigner dans un grand bac d’eau.', '2016-01-01', 12, 6),
(111, 'Nougat', 1, '31642695078.jpg', 'Je suis arrivée fin Juillet chez les pattenronds alors que je n’avais que 5 jours. J\'ai d’abord passé une première nuit à la clinique vétérinaire mais je refusais de s’alimenter. J\'ai donc été récupérée par la présidente de l’association qui a veillé jour et nuit pendant 1 mois, le temps que j\' apprenne à boire au biberon, à faire mes besoins seuls et finalement à manger une bonne petite pâtée toute seule. Une fois en pleine forme, j\'ai pu rejoindre une famille d’accueil dans laquelle les autres chats m\'ont appris à rentrer mes petites griffes et ne pas utiliser mes dents sans raison valable ! Pleine d’énergie mais aussi pleine de tendresse, j\'aime courir partout et jouer avec n’importe quoi autant que faire de gros câlins à son humain.', '2021-07-22', 11, 2),
(115, 'Marco', 0, '31644957916.jpg', 'Je suis un jeune chat de 3 ans qui traîne derrière moi un lourd passé dans la rue. J\'en ai gardé des petites cicatrices sur ma tête et un tempérament assez craintif. Il me faudra un peu de temps pour m’adapter à mon nouveau domicile et à vous faire confiance. Au départ, je resterais caché sous un lit ou un meuble. Mais si vous faites preuve de patience et de douceur, au fil des jours, je vous donnerais ma confiance. Et là, vous découvrirez le vrai Marco, un chat très attachant, ronronnant facilement, aimant les caresses et les gratouilles. Je suis un gentil matou, un tantinet gourmand et qui communique beaucoup avec les humains par petits miaulements. Je suis aussi joueur : je m\'amuserais seul, avec vous ou un copain chat. J\'aime m’allonger à vos pieds, car j\'apprécie la compagnie humaine sans toutefois sauter sur vos genoux pour dormir. Toutefois, je serais toujours à votre proximité et ronronnerais à la moindre caresse. J\'aime les câlins sans être pot de colle et je m’entends avec les autres chats.', '2019-01-01', 13, 2),
(122, 'Venus', 1, '31644961773.jpg', 'Je suis une tortue mauresque, je mesure environ 18 cm et mon espérance de vie est de 100 ans. Je suis végétarienne, je me nourris principalement de plantes sauvages.', '2014-01-01', 12, 6),
(124, 'Sweety', 1, '31645010035.jpg', 'Je suis une petite boule de poil pleine de vie, j\'adooore jouer avec tout et n’importe quoi, même si parfois, je suis un peu brute dans mes mouvements ! Je suis un peu timide quand je ne connais pas mais une fois bien en confiance, je deviens très câline et je vous accueillerez avec des séances de ronrons non-stop. Âgée d’un an et demi, je suis une jeune chatte extrêmement vive et énergique ayant besoin de se dépenser ! Un foyer avec un copain chat joueur (mâle ou femelle) serait l’idéal pour moi. Toutefois, je ne passe pas tout mon temps à faire la fofolle. J\'ai des moments de calme pendant lesquels j\'aime m\'assoupir près du chauffage ou vous montrer mon affection en frottant doucement ma tête contre la vôtre (ça peut durer très longtemps !). Je ne suis pas bavarde, je suis une chatte plutôt discrète qui respecte votre tranquillité. Mais attention je suis exigeante sur mon dîner, une bonne pâtée et c’est la clef du succès !', '2020-01-01', 13, 2),
(125, 'Albi', 1, '31645021281.jpg', 'Je suis un python royal et je mesure 1m20. J\'ai un régime particulier, je mange des rats tous les 15 jours. Je vis dans un terrarium sec.', '2017-01-01', 12, 6),
(128, 'Trois', 0, '31645021515.jpg', 'Je suis un python royal et je mesure 1m20. J\'ai un régime particulier, je mange des rats tous les 15 jours. Je vis dans un terrarium sec. J\'aime pouvoir me cacher et me balader dans le terrarium.', '2015-01-01', 12, 6),
(129, 'Panthère', 1, '31645026414.jpg', 'Je suis un serpent des blés et je mesure 100 cm. Je suis carnivore, je mange des souris adultes ou petits rats une fois toutes les 2 semaines. Je vis dans un terrarium semi arboricole. J\'aime pouvoir me cacher et me balader dans le terrarium car je suis semi-arboricole.', '2017-01-01', 12, 6),
(130, 'Obsucurus', 0, '31645026534.jpg', 'Je suis un serpent ratier gris et je mesure 1m20. Je suis carnivore, je mange des souris adultes ou petits rats une fois toutes les 2 semaines. Je suis un très bon mangeur ! Je vis dans un terrarium semi arboricole. J\'aime pouvoir me cacher et me balader dans le terrarium car je suis semi-arboricole.', '2016-01-01', 12, 6),
(132, 'Korinn', 1, '31645181314.jpg', 'Je suis une chatte très sociable, hyper proche de l’humain à la limite collante, douce et très gentille. Je suis mille fois reconnaissante d’avoir été sortie de la rue où je galérais depuis plusieurs semaines. Je suis actuellement en fin de traitement pour un coryza que j\'ai attrapé lors de mon abandon. Je serais heureuse d’être la compagne à 4 pattes d’un couple, d’une famille avec des enfants aussi doux que moi ou d’une personne seule.', '2019-01-01', 13, 2),
(134, 'Bella', 1, '31645363008.jpg', 'Je suis un petit ange sur pattes ! D’une douceur incroyable, je suis âgée de 5 mois et je suis extrêmement sociable aussi bien avec les humains, les enfants et les autres chats. Je vous suis partout, adorant partager votre quotidien, venir dormir sur ou près de vous, recherchant votre présence et contact. Mes futurs adoptants devront également être des cordon-bleu, car j\'ai été élevée à la nourriture faite maison, j\'ai du mal à accepter la nourriture industrielle.', '2021-02-01', 13, 2),
(135, 'Genos', 0, '31645449314.jpg', 'Je suis un python royal et je mesure 1m20. Je suis carnivore, je mange des rats tous les 15 jours. Je vis dans un terrarium sec. J\'aime pouvoir me cacher et me balader dans le terrarium.', '2017-01-01', 12, 6),
(136, 'Malé', 1, '31645803654.jpg', 'Je suis une jeune femelle labrador de 3 ans. Je suis très sociable avec les humains, les enfants et les chiens. Habituée à la vie en appartement, je préfère maintenant une vie en maison avec jardin. J\'ai besoin d\'une famille assez présente. J\'adore les balades et jouer avec vous.', '2019-01-01', 14, 3),
(138, 'Tina', 1, '31645803784.jpg', 'Je suis une jeune minette d’environ 1 an, très très câline. Je suis très sociable, proche de l’homme, une vrai boite à ronrons ! J\'aurais besoin d’un accès extérieur, jardin, car j\'ai été habituée dans ma précédente famille.', '2021-01-01', 14, 2),
(139, 'Pruneau', 0, '31645803865.jpg', 'Je suis absolument craquant avec mes yeux miel surlignés de noir, mon beau pelage tigré blanc et mon petit museau rose. Mais je suis surtout un chat ayant un super caractère : d’une patience extrême, d’une douceur incroyable, d’un calme olympien et d’une affection incroyable. Une fois en confiance (très vite), je suis très câlin. J\'adore la proximité avec l’humain. J\'aime tout particulièrement venir me blottir tout contre vous afin que vous me grattouilliez mon petit ventre. Je suis un chat très facile à vivre qui s’adapte facilement à un nouvel environnement, ne fait pas de bêtises et est très calme pendant les transports dans ma caisse. D’un petit gabarit, j\'ai des allures de chaton junior ! Mon seul petit défaut, c’est ma gourmandise : mais je suis tellement adorable qu’on me pardonne tout. Je veux apporter à mes futurs adoptants une tonne d’amour.', '2021-01-01', 13, 2),
(140, 'Eliott', 0, '31645817566.jpg', 'Je fais partie de ces petits bouts un tantinet timides qui ont besoin d’un peu de temps pour s’habituer à vous et à un nouvel environnement. Mais dès que je suis en confiance, je deviens un redoutable joueur et un chaton très proche de vous : je réponds et viens quand vous m’appelez par mon nom et j\'adore m’endormir blotti tout contre votre joue. Âgé de 3 mois et demi, je suis rassuré par la présence d’un autre chat, mais effrayé par les chiens et les lapins !', '2022-01-01', 13, 2),
(141, 'Tina-Alda', 1, '31645817663.jpg', 'Je suis une jeune minette d’environ 8-10 mois. Je suis très câline, avenante, a tendance à suivre mon maître partout dans la maison. J\'ai mes petits moments de folie, où je joue comme une folle. Mais j\'ai un tempérament général plutôt calme. J\'adore les séances télé dans le canapé.', '2022-01-01', 14, 2),
(143, 'Migui', 1, '31645817802.jpg', 'Je suis une petite chatonne de 6 mois, qui est calme, indépendante,  qui aime sa tranquillité, mais apprécie qu\'on vienne me papouiller en offrant mon bidon.\nJ\'adore dormir dans la douche.', '2022-01-01', 14, 2),
(144, 'Sunny', 0, '31645817877.jpg', 'Je suis un jeune chat parfait ! Avec mes grands yeux verts et ma petite oreille noire. Âgé de 11 mois je suis un amour sur pattes. Hyper sociable, j\'adore jouer, je suis vif et super câlinou. Je serais parfait comme 1er chat ou le chat d’un foyer avec ou non des enfants.', '2021-01-01', 13, 2),
(145, 'Moon', 0, '31645817993.jpg', 'Je suis un adorable feu follet. Je suis un jeune chat d’un an et demi qui est hyper facile à vivre. Bien dans ma tête, je suis très sociable, câlin, je m’entends avec les autres chats et je suis tout de suite à l’aise dans un nouvel environnement. Je suis aussi un matou très vif et dynamique qui a besoin de se dépenser. Je recherche un foyer avec impérativement un jardin/grande terrasse sécurisé. Pas d’appartement de petite surface', '2020-01-01', 13, 2),
(146, 'John François Albert 1er', 0, '31645818064.jpg', 'Je suis un boa constrictor, je mesure 2 m. Je suis carnivore, je mange un rat de 150g tous les 15 jours. Je vis dans un grand terrarium avec des branches et des endroits pour me cacher, j’aime aussi me baigner dans un grand bac d’eau.', '2010-01-01', 12, 6),
(147, 'Rocinante', 1, '31646057536.jpg', 'Avec mon miaulement adorable et ma petite frimousse à craquer.Je suis une minette de rêve. Extrêmement câline, je suis également une joueuse invétérée ! Je vous porte le plumeau pour qu’ensemble, nous fassions une partie de jeu endiablée. Une fois fatiguée, je pars me reposer dans mon coin de prédilection. Je suis affectueuse tout en étant indépendante (je ne suis pas un pot de colle). Âgée de 8 mois, je suis facile à vivre pour peu que je puisse me dépenser en jouant.', '2021-01-01', 13, 2),
(148, 'Weasley', 0, '31646057597.jpg', 'Je suis un amoureux éternel… des humains ! Je les adore, je recherche constamment leur attention, réclame des câlins et aime être là où vous vous trouvez. Je suis un jeune ado de 6 mois et demi, d’une extrême douceur, très affectueux et d’une grande gentillesse. Je suis un peu réservé quand je ne connais pas, mais mon amour des humains prend très vite le dessus. Je suis également comme tous les jeunes matous : très joueur. J\'ai cependant un petit pêché mignon (personne n’est parfait) : je suis gourmand. À la moindre odeur de nourriture, j\'arrive en courant.', '2021-01-01', 13, 2),
(149, 'Monya', 0, '31646057670.jpg', 'J\'ai une passion dans sa vie : l’humain ! J\'adore être avec vous, aimant vous observer, suivre vos faits et gestes, venir dormir contre vous, ronronner de plaisir sous vos caresses…Je suis gentille et sociable avec tous dont les autres chats.', '2020-01-01', 13, 2),
(150, 'Buck', 0, '31646170452.jpg', '​Je suis une caille du Japon. On m\'a récupéré dans une clinique vétérinaire. Je suis un petit pépère timide et fuyant avec l\'homme, qui chante de plus en plus et se montre curieux.', '0001-01-01', 15, 11),
(151, 'Birdy', 0, '31646170636.jpg', 'Je suis une perruche du Pennant. Sortie de fourrière, j\'ai été trouvée en pleine rue. Je suis peureuse vis-à-vis de l\'homme mais je suis très attentive ! Je chante énormément et imite quelques sons.', '2020-01-01', 15, 11),
(152, 'Aku', 0, '31646170862.jpg', 'Je suis une ​perruche calopsitte. Sortie de fourrière. Je suis un pépère assez calme, très observateur et qui vient de plus en plus sur vos épaules, je suis moins peureux qu\'à mon arrivée au refuge.', '0001-01-01', 15, 11),
(153, 'Laki', 1, '31646170931.jpg', 'Je suis une perruche calopsitte trouvée blessée devant un portail. J\'avais une patte blessée lors de son arrivée au refuge, qui a bien cicatrisé. Je suis une vraie glu ! Toujours à chercher l\'attention, très gourmande, mais j\'ai mon petit caractère malgré tout !', '0001-01-01', 15, 11),
(154, 'Bruno', 0, '31646171025.jpg', 'Je suis une ​perruche ondulée.​ Avant d\'arriver au refuge, je vivais dans une cage minuscule avec ma copine Luna. Je suis très bavard, soumis avec les autres et sociable.', '0001-01-01', 15, 11),
(155, 'Luna', 1, '31646171089.jpg', 'Je suis une ​perruche ondulée.​ Avant d\'arriver au refuge, je vivais dans une cage minuscule avec mon copain Bruno. Très discrète dans la volière, je suis soumise avec les autres ondulée et je ne cherche pas beaucoup le contact avec vous.', '0001-01-01', 15, 11),
(156, 'Iggy', 0, '31646171637.jpg', 'Je suis comme tout bébé très joueur et curieux, je suis plus indépendant que mes frères et vient à votre contact surtout quand vous avez des peluches (avec lesquels j\'adore jouer !) ou de la nourriture, je suis un petit gourmand...\nJe suis un petit fureton très intelligent, qui est le premier à trouver les bêtises à faire, ou les petits espaces non sécurisés que vous auriez manqués.', '2021-01-01', 15, 12),
(157, 'Chickpea', 0, '31646171728.jpg', 'Je suis une petite crevette adorable, hyper curieux et pot de colle avec vous, les humains, je suis un vrai fan de chaussettes également ! Je suis très suiveur pour le moment, si mes frères ne passent pas avant je reste avec eux, je ne suis pas un grand aventurier, même si je prends petit à petit confiance. J\'ai eu une blessure (malformation ou fractures) à une patte avant mais c\'est maintenant à peine perceptible.', '2021-01-01', 15, 12),
(159, 'Aïka', 1, '31646227768.jpg', 'J\'ai été abandonnée devant le portail du refuge. Obèse à mon arrivée, j\'ai repris une forme normale. Je suis une lapine sensible aux changements alimentaires (diarrhée). Je suis une vraie madame ronchonne ! Je grogne beaucoup, en particulier au moment de mes granulés du soir ou quand on essaie de me manipuler. Je suis une lapine qui a eu du mal avec mon abandon, je n\'ai pas compris ce qu\'il se passait et j\'ai eu beaucoup de difficulté à m\'acclimater, après plusieurs semaines, je fais maintenant confiance aux bénévoles et j\'ai fait de gros progrès sur mon comportement vis-à-vis  de l\'humain. Il reste du travail, mais je suis une lapine vraiment attachante, j\'aurais simplement besoin d\'une famille douce et patiente, qui saura me comprendre et m\'accorder du temps.', '0001-01-01', 15, 13),
(160, 'Tempo', 0, '31646237686.jpg', 'Je suis un furet très vif, encore jeune donc foufou, j\'ai besoin d\'activité, et je sais me faire entendre si je n\'ai pas ma dose d\'activité quotidienne ou que je souhaite attirer votre attention (gratte les barreaux, mords son bac..) je fais très facilement de grandes balades en harnais, je marche très bien et en étant attentif on sait quand je veux se reposer (je viens au pied et grimpe sur vos jambes) je connais les chiens mais dois encore m\'habituer, je peux parfois les pincer. Je ne suis pas mordeur avec l\'homme, mais évidemment il faut faire attention, particulièrement dans les séances de jeu.', '0001-01-01', 15, 12),
(161, 'Bouli', 0, '31646237795.jpg', 'Je suis un hamster nain. Suite à l\'adoption d\'un couple en animalerie, un particulier s\'est laissé débordé par les portées. Il a donc fait appel au refuge afin de me prendre en charge ainsi que mes frères et sœurs.  Je suis sociable, gentil et actif !', '2020-09-10', 15, 5),
(162, 'Kora', 1, '31646237949.jpg', 'Je suis un hamster nain. Suite à l\'adoption d\'un couple en animalerie, un particulier s\'est laissé débordé par les portées. Il a donc fait appel au refuge afin de me prendre en charge ainsi que mes frères et sœurs . Je suis sociable, gentil et actif !', '2020-09-10', 15, 5),
(163, 'Réglisse', 0, '31646238535.jpg', 'Je vivais dans un clapier dans un jardin, je m\'acharnais sans cesse à vouloir partir, un jour où j\'ai encore réussi à m\'en échapper, j\'ai terminé mon escapade chez l\'une des bénévoles ! J\'ai attaqué le chien de la famille et également la maman... Je me montrais très agressif. Après discutions avec ma propriétaire, la bénévole a apprit qu\'elle souhaitait se séparer de moi car justement j\'étais trop agressif. Je suis donc arrivée au refuge. Petite sensibilité respiratoire, je ne pourrais pas vivre dans un milieu trop humide. Au vu de ma description, j\'ai été stérilisé en urgence au moment de mon arrivée. Depuis, je suis un véritable amour, pas une seule fois je me suis montré agressif avec les bénévoles ou même les visiteurs ! Alors qu\'on &quot;m\'embête&quot; dans mon espace, quand on prend ma gamelle ou qu\'on change mon clapier... Je suis un petit lapin très curieux qui vient même volontiers chercher quelques gratouilles.', '0001-01-01', 15, 13),
(164, 'Mélody', 1, '31646238707.jpg', 'J\'ai été trouvée dans un logement avec d\'autres animaux, malheureusement ma propriétaire a décédée 13 jours avant, et nous sommes restés dans le logement, et beaucoup sont décédés... Je suis arrivée au refuge très maigre, apeurée, avec des griffes très longues et énormément de bourres de poils/nœuds, j\'étais dans un sale état, non entretenue depuis des mois... Je vais maintenant beaucoup mieux ! Je dois seulement reprendre un peu de poids. J\'ai mon petit caractère, je n\'aime pas beaucoup qu\'on touche à mes affaires, et je n\'ai pas eu beaucoup de contact avec l\'homme, j\'ai besoin de temps avant de vous faire confiance.', '0001-01-01', 15, 13),
(165, 'Igloo', 0, '31646239004.jpg', 'Je suis arrivé avec ma maman Neige, suite à une erreur de sexage mon adoptante s\'est retrouvée avec un couple, non stérilisé. Je suis donc née, la personne ne pouvant pas assumer mes frères et sœurs, elle nous a confiée au refuge. Je suis un petit bonhomme très curieux, je suis le plus grand de la bande.', '2021-03-09', 15, 13),
(166, 'Pépite', 0, '31646239070.jpg', 'Je suis arrivé avec ma maman Neige, suite à une erreur de sexage mon adoptante s\'est retrouvée avec un couple, non stérilisé. Je suis donc née, la personne ne pouvant pas assumer mes frères et sœurs, elle nous a confiée au refuge. Je suis hyper curieux et sociable.', '2021-03-09', 15, 13),
(167, '​Burberry', 1, '31646241875.jpg', 'J\'ai été abandonnée  par mes anciens propriétaires (Trop de dégâts, manque de temps, lassitude, installation non esthétique). Je suis timide au premier abord, mais je me détends très rapidement et prends vite mes marques ! Je suis une puce très vive le soir venu, bien dans mes pattes et qui adore le bois ! Je suis à adopter avec Groseille.', '2019-03-01', 15, 5),
(168, 'Groseille', 1, '31646242008.jpg', 'J\'ai été abandonnée par mes anciens propriétaires (Trop de dégâts, manque de temps, lassitude, installation non esthétique). Plutôt réservée, c\'est seulement après quelques jours que je commencerais à venir de plus en plus vers vous, à chercher le contact et à prendre des friandises dans vos mains, je suis beaucoup ma copine Groseille et je me rassure auprès d\'elle.', '2019-06-01', 15, 5),
(169, '​Galopin', 0, '31646242757.jpg', 'Je viens d\'une portée de souris non désirée chez un particulier. Je suis un pépère adorable, qui sors au moindre bruit. Je suis un peu timide au premier abord, mais je me montre très très vite curieux et aventurier ! Je viens sentir les doigts mais n\'aime pas être attrapé. Je devrais vivre seul dans mon futur foyer. J\'aurais besoin d\'une cage spacieuse mais bien sécurisée (attention à l\'espace entre les barreaux !). J\'ai également besoin d\'avoir une bonne couche de litière pour creuser et faire mon nid. Je suis une petite souris extrêmement active, vive, et curieuse.', '2021-02-01', 15, 5),
(170, 'Venus', 1, '31646251152.jpg', 'J\'ai été confiée au refuge suite au décès de ma propriétaire. Je suis une petite lapine assez flipette au quotidien avec les gens, en raison de mes conditions de vie passée, mais j\'ai fait de gros progrès, je suis assez curieuse, mais j\'ai besoin de la présente de ma sœur Isis pour être rassurée pour le moment. Je suis malheureusement porteuse du parasite e-cuniculi et j\'ai parfois des &quot;crises&quot; qui nécessitent un traitement.', '0001-01-01', 15, 13),
(171, 'Isis', 1, '31646251193.jpg', 'J\'ai été confiée au refuge suite au décès de ma propriétaire. Je suis une lapine discrète, sociable, qui a besoin de temps avant d\'accorder sa confiance aux humains.  Je suis malheureusement porteuse du parasite e-cuniculi et j\'ai parfois des &quot;crises&quot; qui nécessitent un traitement.', '0001-01-01', 15, 13),
(172, 'Oxana', 1, '31646251547.jpg', 'J\'ai été trouvée dans un logement avec d\'autres animaux, malheureusement ma propriétaire a décédée 13 jours avant, et nous sommes restés dans le logement, et beaucoup sont décédés... Le refuge m\'a accueilli, je suis une petite chinchilla très réservée, encore peureuse de la main de l\'homme, il reste encore du travail pour m\'apprivoiser, mes anciennes conditions de vie n\'ont pas du aider, je suis une puce vraiment méfiante. J\'espère trouver une nouvelle famille avec ma copine Oural.', '0001-01-01', 15, 5),
(173, 'Oural', 1, '31646251613.jpg', 'J\'ai été trouvée dans un logement avec d\'autres animaux, malheureusement ma propriétaire a décédée 13 jours avant, et nous sommes restés dans le logement, et beaucoup sont décédés... Le refuge m\'a accueilli, je suis comme ma copine Oxana, plutôt réservé, mais je progresse rapidement, vous pourrez me toucher sans que je ne cherche à fuir et viens de plus en plus chercher les friandises dans nos mains.', '0001-01-01', 15, 5),
(174, 'Crispy', 1, '31646316806.jpg', 'J\'ai été capturée avec 13 autres lapins suite à un signalement, quelqu\'un nous avait simplement balancés tous en pleine nature...  Je suis une lapine plutôt discrète sauf quand il faut manger.. Là je sais me faire entendre et attaque les grilles. Je commence cependant à perdre ce comportement, mon séjour dehors avec peu de nourriture a dû avoir un impact. Je suis une lapine qui accepte assez bien le contact humain.', '0001-01-01', 15, 13),
(175, 'Takara', 1, '31646317016.jpg', 'Une personne qui aménageait son logement nous a trouvés dans sa grange, l\'ancien propriétaire n\'a pas jugé nécessaire de nous emmener avec lui.', '2021-01-01', 15, 13),
(176, 'Pompom', 0, '31646317105.jpg', 'J\'ai été trouvé dans un parc par une promeneuse. Je suis actuellement totalement sous le contrôle de mes hormones, je marque, monte tout ce que je peux et je me montre agressif sur mon territoire. Nul doute que je serais un petit amour après ma castration.', '0001-01-01', 15, 13),
(177, 'Pandora', 1, '31646317179.jpg', 'Mon ancienne famille ne pouvait plus s\'occuper de nous, je suis née d\'une portée non contrôlées, je m\'échappais avec mes copains du jardin pour aller sur le parking de la résidence.', '2021-04-10', 15, 13),
(178, 'Daisy', 1, '31646317259.jpg', 'J\'ai été livré à moi-même dans un jardin, avec d\'autres lapins, j\'ai été prise en charge  en urgence. J\'ai de gros soucis dentaires, j\'ai l\'œil gauche purulent et j\'éternue quelques fois, je suis actuellement toujours sous traitement. Je suis une lapine qui malgré son passé est adorable avec l\'homme, vraiment curieuse et gourmande ! J\'ai parfois du mal avec les soins et mon traitement mais je me laisse toujours faire, je suis une petite mère très courageuse.', '0001-01-01', 15, 13),
(179, 'Miko', 0, '31646317317.jpg', 'J\'ai été abandonné dans la rue par un monsieur, une voisine m\'a récupérée et m\'a déposée au refuge. J\'avais une malocclusion dentaire sur mes incisives, toutes ont donc été retirées, je ne peux donc plus couper mes aliments, mais je peux toujours manger normalement (granulés, petits brins de foins ou d\'herbe et légumes/fruits coupés en petits morceaux). Je suis un lapin très gentil, doux, propre dans son clapier, qui devient de plus en plus câlin avec l\'humain, un petit amour !', '2021-01-01', 15, 13),
(180, 'Lilo', 0, '31646317380.jpg', 'J\'ai été trouvé errant, mes propriétaires n\'ont pas été retrouvés. Je suis un petit mâle très calme, qui s\'est rapidement habitué au refuge, je suis plutôt propre et viens facilement au contact.', '0001-01-01', 15, 13),
(181, 'Fanta', 1, '31646317468.jpg', 'Je suis une vraie décoratrice d\'intérieure, curieuse et posée, j\'aime la tranquillité mais accepte volontiers les petites friandises qu\'on me donne.', '2018-01-01', 15, 13),
(182, 'Maddy', 1, '31646317579.jpg', 'J\'ai été trouvée errante par des particuliers fin janvier. Je suis là depuis peu au refuge. Pour le moment, je suis une lapine plutôt calme et curieuse.', '0001-01-01', 15, 13),
(183, 'Benny', 0, '31646317640.jpg', 'J\'ai été trouvé dans la rue. Fan incontesté de l\'humain, des câlins, de l\'attention ! Je suis une vraie crème pleine de poils. Je suis également très attiré par la nourriture, comme je suis arrivé un peu maigrichon... Je suis un grand lapin, très curieux et qui fait beaucoup de flops.', '0001-01-01', 15, 13);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
